---
title: "July_18_Updates"
author: "Deepa"
date: "July 17, 2017"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

##Summary of work to date

###What we've agreed on so far
1. The sample will be restricted to those born in or before 1958 (in practice, this only excludes the younger spouses of the target population in this survey)
2. Study design will be difference-in-difference
3. Treated countries passed a new serious or general adult family health policy the involved a leave period of at least 6 months, as identified by Ilona and Efe [i.e. Belgium, Denmark and Netherlands]
4. Policy introduction will be coded 1/0 (rather than the actual duration of leave as a continuous exposure variable)
5. We will include a flexible term for age and cluster standard errors at the individual ID and country levels
6. All analyses will be stratified by sex
7. Outcome will be work status (1/0)
7. Research Question: What is the effect of introducting an adult family health policy of at least 6 months on the probability of working?

##Things that need to be decided 
###1. The specification of the diff-in-diff model (which in turn informs selection of the control group)

####Option 1: Each treated country gets its own model specified like this: 
$Y_{ict} = \alpha + \beta_{1}\times Post_{ct} + \beta_{2}\times treated_{c} + \beta_{3}\times post\times treated_{ict} + \sum_{k=1}^{k=3}age^k_{it}  + \rho_{ci}$

Y = P(working); i = individual; c = country; t=year; $\rho$ = errors  
Post = 1/0 variable indicating the post-policy period  
Treated = 1/0 variable indicating whether the country was in the treated or control group  
The effect of interest is $\beta_{3}$. 

Why Option 1?
The policies the countries passed were very different so stratifying by country allows them each to have different effects.

Control group? 
Already decided from work so far.

####Option 2: All countries modelled together
$Y_{ict} = \alpha + \beta_{1}\times Post_{ict} + \sum_{k=1}^{k=3}age^k_{it} + \rho_{ci}$

i = individual; c = country; t=year; $\rho$ = errors  
Y = P(working)  
Post = time-varying 1/0 indicator of whether the individual is in the post-policy period of at treated country (remains 0 at all time points for individuals in a control country)  
The effect of interest is $\beta_{1}$. 

Why Option 2? 
More efficient and also typically how these multiple intervention type diff and diff designs are done.

Control group?  
-Jay's idea: moving windows (ineffecient)  
-Visual trends looking at each intervention time point (treatment countries grouped together)  
-Regression similar to what has been done so far to consider the significant of interaction terms in different years, with treatment countries grouped together.

##2. Additional country-level covariates if necessary
Option 1: We include a linear time trend  
Option 2: Augment our dataset with country-level variables including unemployment rates and GDP per capita, obtained through World Bank



